// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MoneyManager.Models;
using System;

namespace MoneyManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoneyManager.Models.Bank", b =>
                {
                    b.Property<short>("BankId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("BankId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("MoneyManager.Models.Deposit", b =>
                {
                    b.Property<int>("DepositId")
                        .ValueGeneratedOnAdd();

                    b.Property<short?>("BankId");

                    b.Property<byte>("CapitalizationTermsPerYear");

                    b.Property<DateTime>("ClosingDate");

                    b.Property<int>("Currency");

                    b.Property<bool>("HasCapitalization");

                    b.Property<decimal>("InitialFund");

                    b.Property<decimal>("InterestRate");

                    b.Property<DateTime>("OpeningDate");

                    b.HasKey("DepositId");

                    b.HasIndex("BankId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("MoneyManager.Models.Deposit", b =>
                {
                    b.HasOne("MoneyManager.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");
                });
#pragma warning restore 612, 618
        }
    }
}
